# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.2-343-g1b48293
_src_path: gh:acsone/oca-addons-repo-template
additional_ruff_rules: []
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 18.0
org_name: ACSONE SA/NV
org_slug: acsone
postgres_image: ''
rebel_module_groups: []
repo_description: Odoo modules to support the IFRS 15 accounting standard (https://en.wikipedia.org/wiki/IFRS_15).
    These modules implement the concept of Performance Obligation.
repo_name: Odoo modules to support IFRS 15 accounting
repo_slug: account-performance-obligation
repo_website: https://github.com/acsone/account-performance-obligation
use_pyproject_toml: true
use_ruff: true

